import = function() {
  
  A = read.csv("data/A.csv")
  B = read.csv("data/B.csv")
  C = read.csv("data/C.csv")
  D = read.csv("data/D.csv")
  E = read.csv("data/E.csv")
  F = read.csv("data/F.csv")
  G = read.csv("data/G.csv")
  H = read.csv("data/H.csv")
  I = read.csv("data/I.csv")
  J = read.csv("data/J.csv")
  K = read.csv("data/K.csv")
  L = read.csv("data/L.csv")
  M = read.csv("data/M.csv")
  N = read.csv("data/N.csv")
  O = read.csv("data/O.csv")
  P = read.csv("data/P.csv")
  Q = read.csv("data/Q.csv")
  R = read.csv("data/R.csv")
  S = read.csv("data/S.csv")
  T = read.csv("data/T.csv")
  U = read.csv("data/U.csv")
  V = read.csv("data/V.csv")
  W = read.csv("data/W.csv")
  X = read.csv("data/X.csv")
  Y = read.csv("data/Y.csv")
  Z = read.csv("data/Z.csv")
  
}