PC2Area = function(PC) {
  if(is.na(PC))                                                                                                      return("Unknown")
  if( PC %in% c(2600, 2601, 2610) )                                                                                  return("Canberra CBD")
  if( PC >= 2601 && PC <= 2609 )                                                                                     return("Canberra Metro")
  if( PC >= 1100 && PC <= 1299 || PC %in% c(2000, 2001, 2007, 2009) )                                                return("Sydney CBD")
  if( PC >= 2002 && PC <= 2234 )                                                                                     return("Sydney Metro")
  if( PC >= 2640 && PC <= 2660 )                                                                                     return("Riverina Area")
  if( PC >= 2500 && PC <= 2534 )                                                                                     return("Wollongong")
  if( PC >= 2265 && PC <= 2333 )                                                                                     return("Newcastle")
  if( PC >= 2413 && PC <= 2484 || PC >= 2460 && PC <= 2465 || PC == 2450 )                                           return("Northern Rivers")
  if( PC >= 3000 && PC <= 3006 || PC == 3205 || PC >= 8000 && PC <= 8399 )                                           return("Melbourne CBD")
  if( PC >= 3000 && PC <= 3207 )                                                                                     return("Melbourne Metro")
  if( PC %in% c(4000, 4001, 4003) || PC >= 9000 && PC <= 9015 )                                                      return("Brisbane CBD")
  if( PC >= 4000 && PC <= 4207 || PC >= 4300 && PC <= 4305 || PC >= 4500 && PC <= 4519 )                             return("Brisbane Metro")
  if( PC >= 4208 && PC <= 4287 )                                                                                     return("Gold Coast")
  if( PC >= 4550 && PC <= 4575 )                                                                                     return("Sunshine Coast")
  if( PC %in% c(5000, 5001, 5004, 5005, 5810, 5839) || PC >= 5880 && PC <= 5889 )                                    return("Adelaide CBD")
  if( PC >= 5000 && PC <= 5119 )                                                                                     return("Adelaide Metro")
  if( PC %in% c(6000, 6001, 6004, 6827) || PC >= 6830 && PC <= 6832 || PC >= 6837 && PC <= 6849 )                    return("Perth CBD")
  if( PC >= 6000 && PC <= 6199 )                                                                                     return("Perth Metro")
  if( PC %in% c(7000, 7001) )                                                                                        return("Hobart CBD")
  if( PC >= 7002 && PC <= 7099 )                                                                                     return("Hobart Metro")
  if( PC >= 0800 && PC <= 0832 )                                                                                     return("Darwin Metro")
  if( PC >= 0200 && PC <= 0299 )                                                                                     return("ACT PO Box or LVR")
  if( PC >= 2600 && PC <= 2620 || PC >= 2900 && PC <= 2920 )                                                         return("Rest of ACT")
  if( PC >= 1000 && PC <= 1999 )                                                                                     return("NSW PO Box or LVR")
  if( PC >= 2235 && PC <= 2999 )                                                                                     return("Rest of NSW")
  if( PC >= 8000 && PC <= 8999 )                                                                                     return("VIC PO Box or LVR")
  if( PC >= 3208 && PC <= 3999 )                                                                                     return("Rest of VIC")
  if( PC >= 9000 && PC <= 9999 )                                                                                     return("QLD PO Box or LVR")
  if( PC >= 4208 && PC <= 4299  || PC >= 4306 && PC <= 4499  || PC >= 4520 && PC <= 4999 )                           return("Rest of QLD")
  if( PC >= 5800 && PC <= 5999 )                                                                                     return("SA PO Box or LVR")
  if( PC >= 5000 && PC <= 5799 || PC >= 5825 && PC <= 5854 )                                                         return("Rest of SA")
  if( PC >= 7800 && PC <= 7999 )                                                                                     return("TAS PO Box or LVR")
  if( PC >= 7100 && PC <= 7999 )                                                                                     return("Rest of TAS")
  if( PC >= 6800 && PC <= 6999 )                                                                                     return("WA PO Box or LVR")
  if( PC >= 6200 && PC <= 6999 )                                                                                     return("Rest of WA")
  if( PC >= 0900 && PC <= 0999 )                                                                                     return("NT PO Box or LVR")
  if( PC >= 0833 && PC <= 0899 )                                                                                     return("Rest of NT")
  return("XXXX")
}
## to check temperory variable Area holds all results
Area = sapply(UM$Postcode, PC2Area)
## shows first afew unmatched postcode
head(UM$Postcode[Area=="XXXX"])
## write new column Area
UM$Area = sapply(UM$Postcode, PC2Area)

write.csv(UM, file = "UM.csv")
